#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Modified by p0n3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	mem_proc = mem_free/mem_total*100
	# full text
	if (type == "swap")
		printf("%.1fG\n", (swap_total-swap_free)/1024/1024)
	else {
		printf("%.1fG (%d%%)\n", mem_free/1024/1024, mem_proc)
		printf("%.1fG\n", mem_free/1024/1024)
	}

	#if(mem_proc > 40) {
	#	printf("#00FF00\n");
	#} else 
	if(mem_proc < 20) {
		printf("#FF0000\n");
	} 
	else if (mem_proc < 40) {
		printf("#FFFC00\n");		
	}
}
' /proc/meminfo
